// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/body" | "/build" | "/dashboard" | "/edit-program" | "/exercises" | "/forge" | "/history" | "/library" | "/mind" | "/onboarding" | "/privacy" | "/profile" | "/profile/edit-mission" | "/profile/empire" | "/profile/growth" | "/profile/mission" | "/profile/settings" | "/schedule" | "/spirit" | "/systems" | "/workout/[id]" | "/workout/[id]/edit" | "/workout/ares/[day]" | "/workout/ares/history" | "/workout/ares/leaderboard" | "/workout/program/[day]" | "/workout/squeeze"
type AppRouteHandlerRoutes = "/api/ai/ares-generate" | "/api/ai/custom-program-generate" | "/api/ai/debrief" | "/api/ai/debrief-personalized" | "/api/ai/mind-sprint" | "/api/ai/mission-brief" | "/api/ai/morning-protocol" | "/api/ai/program-generate" | "/api/ai/quarterly-review" | "/api/ai/squeeze-generate" | "/api/ai/workout" | "/api/checkout" | "/api/nap-squeeze" | "/api/webhooks/stripe"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/ares-generate": {}
  "/api/ai/custom-program-generate": {}
  "/api/ai/debrief": {}
  "/api/ai/debrief-personalized": {}
  "/api/ai/mind-sprint": {}
  "/api/ai/mission-brief": {}
  "/api/ai/morning-protocol": {}
  "/api/ai/program-generate": {}
  "/api/ai/quarterly-review": {}
  "/api/ai/squeeze-generate": {}
  "/api/ai/workout": {}
  "/api/checkout": {}
  "/api/nap-squeeze": {}
  "/api/webhooks/stripe": {}
  "/body": {}
  "/build": {}
  "/dashboard": {}
  "/edit-program": {}
  "/exercises": {}
  "/forge": {}
  "/history": {}
  "/library": {}
  "/mind": {}
  "/onboarding": {}
  "/privacy": {}
  "/profile": {}
  "/profile/edit-mission": {}
  "/profile/empire": {}
  "/profile/growth": {}
  "/profile/mission": {}
  "/profile/settings": {}
  "/schedule": {}
  "/spirit": {}
  "/systems": {}
  "/workout/[id]": { "id": string; }
  "/workout/[id]/edit": { "id": string; }
  "/workout/ares/[day]": { "day": string; }
  "/workout/ares/history": {}
  "/workout/ares/leaderboard": {}
  "/workout/program/[day]": { "day": string; }
  "/workout/squeeze": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
