// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/body/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/body">> = Specific
  const handler = {} as typeof import("../../../src/app/body/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/build">> = Specific
  const handler = {} as typeof import("../../../src/app/build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/edit-program/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edit-program">> = Specific
  const handler = {} as typeof import("../../../src/app/edit-program/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/exercises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exercises">> = Specific
  const handler = {} as typeof import("../../../src/app/exercises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forge">> = Specific
  const handler = {} as typeof import("../../../src/app/forge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../src/app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../../src/app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/mind/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mind">> = Specific
  const handler = {} as typeof import("../../../src/app/mind/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/edit-mission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/edit-mission">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/edit-mission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/empire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/empire">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/empire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/growth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/growth">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/growth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/mission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/mission">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/mission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/spirit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/spirit">> = Specific
  const handler = {} as typeof import("../../../src/app/spirit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/systems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems">> = Specific
  const handler = {} as typeof import("../../../src/app/systems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workout/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workout/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/workout/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workout/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workout/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/workout/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workout/ares/[day]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workout/ares/[day]">> = Specific
  const handler = {} as typeof import("../../../src/app/workout/ares/[day]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workout/ares/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workout/ares/history">> = Specific
  const handler = {} as typeof import("../../../src/app/workout/ares/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workout/ares/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workout/ares/leaderboard">> = Specific
  const handler = {} as typeof import("../../../src/app/workout/ares/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workout/program/[day]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workout/program/[day]">> = Specific
  const handler = {} as typeof import("../../../src/app/workout/program/[day]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workout/squeeze/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workout/squeeze">> = Specific
  const handler = {} as typeof import("../../../src/app/workout/squeeze/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/ares-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/ares-generate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/ares-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/custom-program-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/custom-program-generate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/custom-program-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/debrief-personalized/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/debrief-personalized">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/debrief-personalized/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/debrief/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/debrief">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/debrief/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/mind-sprint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/mind-sprint">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/mind-sprint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/mission-brief/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/mission-brief">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/mission-brief/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/morning-protocol/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/morning-protocol">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/morning-protocol/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/program-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/program-generate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/program-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/quarterly-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/quarterly-review">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/quarterly-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/squeeze-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/squeeze-generate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/squeeze-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/workout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/workout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/workout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/nap-squeeze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nap-squeeze">> = Specific
  const handler = {} as typeof import("../../../src/app/api/nap-squeeze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
