-- ============================================================
-- Fuel rotations (FOR-238) — 2026-09-17
-- GENERATED by scripts/fuel-seed-sql.mjs from fixtures/fuel-seed-rotation-b.json.
-- Do not edit by hand; edit the fixture and regenerate.
--
-- ADDITIVE ONLY: two new tables, the 5 new meals, and both rotations'
-- membership. No column on fuel_meals changes and no rotation-A meal row is
-- touched. A meal belongs to many rotations — three are in both — so
-- membership is a join, not a column, and a meal in two rotations is ONE
-- meal row. Each membership carries the rotation's DEFAULT week; a plan's own
-- week stays the athlete's. rotation_note stays human-readable colour and
-- nothing parses it. Dated after 20260916 so it sorts after everything it
-- references.
-- ============================================================

-- ── fuel_rotations: the named fortnights, read-only to users ─────────────
CREATE TABLE IF NOT EXISTS public.fuel_rotations (
  slug       text PRIMARY KEY,
  name       text NOT NULL,
  sort_order int  NOT NULL,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.fuel_rotations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fuel_rotations: authenticated read" ON public.fuel_rotations;
CREATE POLICY "fuel_rotations: authenticated read" ON public.fuel_rotations
  FOR SELECT TO authenticated USING (true);
-- No INSERT / UPDATE / DELETE policy: users never write the rotations.

-- ── fuel_rotation_meals: membership, each meal at its default week ───────
-- Meal slugs are foreign keys here too: a slug is a stable identifier, not a
-- label, and renaming one breaks membership (FOR-238 §7).
CREATE TABLE IF NOT EXISTS public.fuel_rotation_meals (
  rotation_slug text NOT NULL REFERENCES public.fuel_rotations(slug),
  meal_slug     text NOT NULL REFERENCES public.fuel_meals(slug),
  week          int  NOT NULL CHECK (week IN (1, 2)),   -- the builder's DEFAULT; PlanEntry.week is the athlete's
  sort_order    int  NOT NULL,
  PRIMARY KEY (rotation_slug, meal_slug)
);
ALTER TABLE public.fuel_rotation_meals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fuel_rotation_meals: authenticated read" ON public.fuel_rotation_meals;
CREATE POLICY "fuel_rotation_meals: authenticated read" ON public.fuel_rotation_meals
  FOR SELECT TO authenticated USING (true);
-- No INSERT / UPDATE / DELETE policy: users never write membership.

-- ── The new meals, from the fixture ──────────────────────────────────────
INSERT INTO public.fuel_meals
  (slug, name, protein_cut, spice_profile, format, active_cook_minutes, total_minutes, servings, protein_g_per_person, perishable_within_days, rotation_note, ingredients)
VALUES
  ('miso-ginger-salmon', 'Miso-ginger glazed salmon, green beans, rice', 'salmon', 'miso-ginger', 'broiled', 15, 25, 2, 42, 3, 'FISH — week 1. Bought fresh at Costco with the main shop, same slot as the lemon-garlic salmon it replaces. Glaze goes on before the broiler, so most of the clock is hands-off.', '[{"item":"salmon","qty_per_person":7.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"green beans","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"white miso paste","qty_per_person":1,"unit":"tbsp","store_section":"Pantry","inferred":true},{"item":"fresh ginger","qty_per_person":1,"unit":"tsp","store_section":"Produce","inferred":true},{"item":"honey","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"low-sodium soy sauce","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"rice","qty_per_person":0.5,"unit":"cup dry","store_section":"Pantry","inferred":true}]'::jsonb),
  ('jerk-thighs', 'Jerk chicken thighs, roasted sweet potato, broccoli', 'chicken_thigh', 'jerk', 'oven-roast', 10, 35, 3, 44, 4, 'Week 2. Same thigh as the chili-lime night, different profile and format — L5 in practice. 10 active minutes; the oven does the rest. Cooks 3 so a leftover night comes free.', '[{"item":"chicken thigh, boneless skinless","qty_per_person":8,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"sweet potato","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"broccoli","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"jerk seasoning","qty_per_person":1,"unit":"tbsp","store_section":"Pantry","inferred":true},{"item":"lime","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true}]'::jsonb),
  ('turkey-meatballs', 'Turkey meatballs, tomato-basil, green beans', 'ground_turkey', 'tomato-basil', 'meatball', 20, 30, 3, 42, 3, 'TURKEY — week 2, in the slot the turkey burgers held. 93/7 ONLY — 99% lean will not hold a meatball together any better than it holds a patty. Reheats better than anything else in either rotation.', '[{"item":"ground turkey 93/7","qty_per_person":8.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"crushed tomatoes","qty_per_person":4,"unit":"oz","store_section":"Pantry","inferred":true},{"item":"fresh basil","qty_per_person":0.25,"unit":"oz","store_section":"Produce","inferred":true},{"item":"onion","qty_per_person":0.25,"unit":"each","store_section":"Produce","inferred":true},{"item":"garlic","qty_per_person":2,"unit":"clove","store_section":"Produce","inferred":true},{"item":"egg","qty_per_person":0.5,"unit":"each","store_section":"Dairy","inferred":true},{"item":"dried oregano","qty_per_person":0.5,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"green beans","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"rice","qty_per_person":0.5,"unit":"cup dry","store_section":"Pantry","inferred":true}]'::jsonb),
  ('tandoori-breast', 'Tandoori chicken breast, cucumber-tomato salad, rice', 'chicken_breast', 'tandoori-yogurt', 'marinate-and-broil', 15, 45, 2, 44, 2, 'Week 2. BREAST not thigh — deliberately, to keep a full pound of margin in the thigh bag, same reason as the stir-fry it replaces. Active time drops 25 → 15 because the marinade is passive. Marinate in the morning or the night before; total_minutes excludes the marinade.', '[{"item":"chicken breast, boneless skinless","qty_per_person":6.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"nonfat greek yogurt","qty_per_person":2,"unit":"oz","store_section":"Dairy","inferred":true},{"item":"tandoori seasoning","qty_per_person":1,"unit":"tbsp","store_section":"Pantry","inferred":true},{"item":"lemon","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true},{"item":"garlic","qty_per_person":2,"unit":"clove","store_section":"Produce","inferred":true},{"item":"cucumber","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true},{"item":"tomato","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"rice","qty_per_person":0.5,"unit":"cup dry","store_section":"Pantry","inferred":true}]'::jsonb),
  ('chipotle-cod-tacos', 'Chipotle-lime cod tacos, cabbage slaw', 'cod_halibut', 'chipotle-lime', 'taco', 15, 20, 2, 40, 3, 'FISH — week 2. BOUGHT ON THE SECOND TRIP, not the main shop — learning L3, same as the blackened cod it replaces. Cod is leaner than salmon, so weigh heavier. THE ONE DELIBERATE L5 EXCEPTION: corn tortillas and cabbage are bought for this meal and nothing else. Approved by Andrew 2026-09-15 on the grounds that it is the most different plate in the rotation and both items are cheap.', '[{"item":"cod or halibut","qty_per_person":8.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"green cabbage","qty_per_person":4,"unit":"oz","store_section":"Produce","inferred":true},{"item":"lime","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"cilantro","qty_per_person":0.25,"unit":"oz","store_section":"Produce","inferred":true},{"item":"corn tortillas","qty_per_person":3,"unit":"each","store_section":"Pantry","inferred":true},{"item":"chipotle powder","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"cumin","qty_per_person":0.5,"unit":"tsp","store_section":"Pantry","inferred":true}]'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, protein_cut = EXCLUDED.protein_cut, spice_profile = EXCLUDED.spice_profile,
  format = EXCLUDED.format, active_cook_minutes = EXCLUDED.active_cook_minutes, total_minutes = EXCLUDED.total_minutes,
  servings = EXCLUDED.servings, protein_g_per_person = EXCLUDED.protein_g_per_person,
  perishable_within_days = EXCLUDED.perishable_within_days, rotation_note = EXCLUDED.rotation_note,
  ingredients = EXCLUDED.ingredients;

-- ── The rotations ────────────────────────────────────────────────────────
INSERT INTO public.fuel_rotations (slug, name, sort_order, note)
VALUES
  ('rotation-a', 'Fortnight One', 1, 'The original eight. Ran Aug 24 – Sep 14, 2026.'),
  ('rotation-b', 'Fortnight Two', 2, 'Five new meals plus the three keepers. Same cut mix as rotation A — ribeye 1, chicken thigh 2, ground turkey 2, fish 2, chicken breast 1 — so the Costco shop is identical in shape and cost. Every spice profile and format is new against rotation A.')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, note = EXCLUDED.note;

-- ── Membership: both rotations, each meal at its default week ────────────
INSERT INTO public.fuel_rotation_meals (rotation_slug, meal_slug, week, sort_order)
VALUES
  ('rotation-a', 'cast-iron-ribeye', 1, 1),
  ('rotation-a', 'chili-lime-thighs', 1, 2),
  ('rotation-a', 'lemon-garlic-salmon', 1, 3),
  ('rotation-a', 'greek-turkey-bowl', 1, 4),
  ('rotation-a', 'garlic-herb-thighs', 2, 5),
  ('rotation-a', 'turkey-burgers', 2, 6),
  ('rotation-a', 'blackened-cod', 2, 7),
  ('rotation-a', 'soy-ginger-stirfry', 2, 8),
  ('rotation-b', 'cast-iron-ribeye', 1, 1),
  ('rotation-b', 'chili-lime-thighs', 1, 2),
  ('rotation-b', 'miso-ginger-salmon', 1, 3),
  ('rotation-b', 'greek-turkey-bowl', 1, 4),
  ('rotation-b', 'jerk-thighs', 2, 5),
  ('rotation-b', 'turkey-meatballs', 2, 6),
  ('rotation-b', 'tandoori-breast', 2, 7),
  ('rotation-b', 'chipotle-cod-tacos', 2, 8)
ON CONFLICT (rotation_slug, meal_slug) DO UPDATE SET
  week = EXCLUDED.week, sort_order = EXCLUDED.sort_order;
