-- ============================================================
-- Fuel soup fortnights (FOR-250) — 2026-10-10
-- GENERATED by scripts/fuel-seed-sql.mjs from fixtures/fuel-seed-rotation-c.json.
-- Do not edit by hand; edit the fixture and regenerate.
--
-- ROWS ONLY: 4 rotations and 32 membership rows. No table, column,
-- constraint, policy or index changes, and no meal row: every member is a meal
-- the library already holds, so this must be applied AFTER
-- 20261005_fuel_library_expansion.sql (fuel_rotation_meals.meal_slug is a
-- foreign key). Rotations A and B are not touched.
--
-- REVERT, exactly:
--   DELETE FROM public.fuel_rotation_meals WHERE rotation_slug IN ('rotation-c1', 'rotation-c2', 'rotation-c3', 'rotation-c4');
--   DELETE FROM public.fuel_rotations WHERE slug IN ('rotation-c1', 'rotation-c2', 'rotation-c3', 'rotation-c4');
-- Safe at any time: a plan stores its own picks and never a rotation slug.
-- ============================================================

-- ── The rotations ────────────────────────────────────────────────────────
INSERT INTO public.fuel_rotations (slug, name, sort_order, note)
VALUES
  ('rotation-c1', 'Soup Fortnight One', 3, 'Week 1 is Fortnight One''s first week with beef and barley stew in place of the ribeye. Week 2 is Fortnight Two''s second week with chicken tortilla soup in place of the jerk thighs.'),
  ('rotation-c2', 'Soup Fortnight Two', 4, 'Week 1 is Fortnight One''s first week with white chicken chili in place of the chili-lime thighs. Week 2 is Fortnight Two''s second week with Italian wedding soup in place of the turkey meatballs.'),
  ('rotation-c3', 'Soup Fortnight Three', 5, 'Week 1 is Fortnight One''s first week with pork green chili in place of the ribeye. Week 2 is Fortnight Two''s second week with lentil and sausage soup in place of the tandoori chicken.'),
  ('rotation-c4', 'Soup Fortnight Four', 6, 'Week 1 is Fortnight One''s first week with turkey chili in place of the Greek turkey bowl. Week 2 is Fortnight Two''s second week with zuppa toscana in place of the jerk thighs.')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, note = EXCLUDED.note;

-- ── Membership: each meal at its default week ────────────────────────────
INSERT INTO public.fuel_rotation_meals (rotation_slug, meal_slug, week, sort_order)
VALUES
  ('rotation-c1', 'beef-barley-stew', 1, 1),
  ('rotation-c1', 'chili-lime-thighs', 1, 2),
  ('rotation-c1', 'lemon-garlic-salmon', 1, 3),
  ('rotation-c1', 'greek-turkey-bowl', 1, 4),
  ('rotation-c1', 'chicken-tortilla-soup', 2, 5),
  ('rotation-c1', 'turkey-meatballs', 2, 6),
  ('rotation-c1', 'tandoori-breast', 2, 7),
  ('rotation-c1', 'chipotle-cod-tacos', 2, 8),
  ('rotation-c2', 'cast-iron-ribeye', 1, 1),
  ('rotation-c2', 'white-chicken-chili', 1, 2),
  ('rotation-c2', 'lemon-garlic-salmon', 1, 3),
  ('rotation-c2', 'greek-turkey-bowl', 1, 4),
  ('rotation-c2', 'jerk-thighs', 2, 5),
  ('rotation-c2', 'italian-wedding-soup', 2, 6),
  ('rotation-c2', 'tandoori-breast', 2, 7),
  ('rotation-c2', 'chipotle-cod-tacos', 2, 8),
  ('rotation-c3', 'pork-green-chili', 1, 1),
  ('rotation-c3', 'chili-lime-thighs', 1, 2),
  ('rotation-c3', 'lemon-garlic-salmon', 1, 3),
  ('rotation-c3', 'greek-turkey-bowl', 1, 4),
  ('rotation-c3', 'jerk-thighs', 2, 5),
  ('rotation-c3', 'turkey-meatballs', 2, 6),
  ('rotation-c3', 'lentil-sausage-soup', 2, 7),
  ('rotation-c3', 'chipotle-cod-tacos', 2, 8),
  ('rotation-c4', 'cast-iron-ribeye', 1, 1),
  ('rotation-c4', 'chili-lime-thighs', 1, 2),
  ('rotation-c4', 'lemon-garlic-salmon', 1, 3),
  ('rotation-c4', 'turkey-chili', 1, 4),
  ('rotation-c4', 'zuppa-toscana', 2, 5),
  ('rotation-c4', 'turkey-meatballs', 2, 6),
  ('rotation-c4', 'tandoori-breast', 2, 7),
  ('rotation-c4', 'chipotle-cod-tacos', 2, 8)
ON CONFLICT (rotation_slug, meal_slug) DO UPDATE SET
  week = EXCLUDED.week, sort_order = EXCLUDED.sort_order;
