-- ============================================================
-- Fuel Phase 1 (FOR-177) — 2026-09-14
-- GENERATED by scripts/fuel-seed-sql.mjs from fixtures/fuel-seed.json.
-- Do not edit by hand; edit the fixture and regenerate.
--
-- Four tables, RLS in the same migration, and the ONE write path for
-- check state. Seeded with Andrew's fortnight rotation: 8 meals,
-- one complete cycle. Protein quantities are sourced; every side quantity
-- is marked "inferred": true in the ingredient JSON and must be presented
-- as an estimate until Andrew corrects it.
-- ============================================================

-- ── fuel_meals: the curated library, read-only to users ──────────────────
CREATE TABLE IF NOT EXISTS public.fuel_meals (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug                   text UNIQUE NOT NULL,
  name                   text NOT NULL,
  protein_cut            text NOT NULL,
  spice_profile          text NOT NULL,
  format                 text NOT NULL,
  active_cook_minutes    int  NOT NULL,
  total_minutes          int,
  servings               int  NOT NULL DEFAULT 2,   -- cooked at, not eaten by: 3 buys a leftover night
  protein_g_per_person   int,
  perishable_within_days int,
  rotation_note          text,
  ingredients            jsonb NOT NULL DEFAULT '[]'::jsonb, -- [{item, qty_per_person, unit, store_section, inferred}]
  active                 boolean NOT NULL DEFAULT true,
  created_at             timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.fuel_meals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fuel_meals: authenticated read" ON public.fuel_meals;
CREATE POLICY "fuel_meals: authenticated read" ON public.fuel_meals
  FOR SELECT TO authenticated USING (true);
-- No INSERT / UPDATE / DELETE policy: users never write the library.

-- ── fuel_household: one row per user, owner-only ─────────────────────────
CREATE TABLE IF NOT EXISTS public.fuel_household (
  user_id             uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  people_count        int NOT NULL DEFAULT 2 CHECK (people_count BETWEEN 1 AND 12),
  nights_per_week     int NOT NULL DEFAULT 4 CHECK (nights_per_week BETWEEN 1 AND 7),
  cook_cap_minutes    int NOT NULL DEFAULT 30 CHECK (cook_cap_minutes BETWEEN 5 AND 180),
  shop_cadence_days   int NOT NULL DEFAULT 14 CHECK (shop_cadence_days IN (7, 14)),
  prep_diversion_pct  int NOT NULL DEFAULT 0 CHECK (prep_diversion_pct BETWEEN 0 AND 90), -- L2, first-class
  dietary_rules       jsonb NOT NULL DEFAULT '{}'::jsonb,
  inventory           jsonb NOT NULL DEFAULT '[]'::jsonb,   -- [{item, qty, unit}]
  store_section_order jsonb NOT NULL DEFAULT '["Produce","Meat & Seafood","Snacks","Dairy","Pantry","Frozen"]'::jsonb,
  updated_at          timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.fuel_household ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fuel_household: owner" ON public.fuel_household;
CREATE POLICY "fuel_household: owner" ON public.fuel_household
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ── fuel_plans: versioned picks, old versions kept (L6, L7) ──────────────
CREATE TABLE IF NOT EXISTS public.fuel_plans (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start     date NOT NULL,
  version        int  NOT NULL CHECK (version >= 1),
  meal_ids       jsonb NOT NULL,   -- [{slug, week, servings}]
  rules_snapshot jsonb NOT NULL,   -- the household as it was when this version was solved
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, week_start, version)
);
ALTER TABLE public.fuel_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fuel_plans: owner" ON public.fuel_plans;
CREATE POLICY "fuel_plans: owner" ON public.fuel_plans
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ── fuel_lists: the checklist, one row per plan version ──────────────────
CREATE TABLE IF NOT EXISTS public.fuel_lists (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id    uuid NOT NULL REFERENCES public.fuel_plans(id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  version    int  NOT NULL CHECK (version >= 1),
  items      jsonb NOT NULL,   -- ListItem[] from src/lib/fuel/solve.ts, with per-item checked
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (plan_id, version)
);
ALTER TABLE public.fuel_lists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fuel_lists: owner" ON public.fuel_lists;
CREATE POLICY "fuel_lists: owner" ON public.fuel_lists
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS fuel_lists_user_version ON public.fuel_lists (user_id, version DESC);
CREATE INDEX IF NOT EXISTS fuel_plans_user_version ON public.fuel_plans (user_id, week_start, version DESC);

-- ── The one write path for check state — the ROW is authoritative ────────
-- One item, one atomic update, returning the whole row's items so the
-- client replaces its render with what the row now says. SECURITY INVOKER:
-- RLS applies, and the WHERE repeats the owner test anyway.
CREATE OR REPLACE FUNCTION public.fuel_set_item_checked(p_list_id uuid, p_key text, p_checked boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  new_items jsonb;
BEGIN
  UPDATE public.fuel_lists
  SET items = (
        SELECT COALESCE(
          jsonb_agg(
            CASE WHEN elem->>'key' = p_key THEN jsonb_set(elem, '{checked}', to_jsonb(p_checked), true) ELSE elem END
            ORDER BY ord
          ), '[]'::jsonb)
        FROM jsonb_array_elements(items) WITH ORDINALITY AS t(elem, ord)
      ),
      updated_at = now()
  WHERE id = p_list_id AND user_id = auth.uid()
  RETURNING items INTO new_items;
  IF new_items IS NULL THEN
    RAISE EXCEPTION 'fuel list % is not yours or does not exist', p_list_id USING ERRCODE = '42501';
  END IF;
  RETURN new_items;
END
$$;
REVOKE EXECUTE ON FUNCTION public.fuel_set_item_checked(uuid, text, boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.fuel_set_item_checked(uuid, text, boolean) TO authenticated;

-- ── Seed: Andrew's fortnight rotation (8 meals), from the fixture ───
INSERT INTO public.fuel_meals
  (slug, name, protein_cut, spice_profile, format, active_cook_minutes, total_minutes, servings, protein_g_per_person, perishable_within_days, rotation_note, ingredients)
VALUES
  ('cast-iron-ribeye', 'Cast-iron ribeye, roasted broccoli, baked russet', 'ribeye', 'salt-and-pepper', 'pan-seared', 10, 25, 2, 48, 4, 'The only steak in the fortnight. Does not reheat — cooks to order, 2 servings.', '[{"item":"ribeye","qty_per_person":8,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"broccoli","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"russet potato","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"olive oil","qty_per_person":0.5,"unit":"tsp","store_section":"Pantry","inferred":true}]'::jsonb),
  ('chili-lime-thighs', 'Sheet-pan chili-lime chicken thighs, broccoli, sweet potato', 'chicken_thigh', 'chili-lime', 'sheet-pan', 10, 35, 3, 44, 2, 'One pan. Best night of the week for a bad day. Cooks 3 so a leftover night comes free.', '[{"item":"chicken thigh, boneless skinless","qty_per_person":8,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"broccoli","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"sweet potato","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"lime","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true},{"item":"chili powder","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"cumin","qty_per_person":0.5,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"garlic powder","qty_per_person":0.5,"unit":"tsp","store_section":"Pantry","inferred":true}]'::jsonb),
  ('lemon-garlic-salmon', 'Lemon-garlic salmon, green beans, rice', 'salmon', 'lemon-garlic', 'pan-seared', 15, 20, 2, 42, 3, 'FISH — week 1. Bought fresh at Costco with the main shop.', '[{"item":"salmon","qty_per_person":7.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"green beans","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"lemon","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true},{"item":"garlic","qty_per_person":2,"unit":"clove","store_section":"Produce","inferred":true},{"item":"rice","qty_per_person":0.5,"unit":"cup dry","store_section":"Pantry","inferred":true}]'::jsonb),
  ('greek-turkey-bowl', 'Greek turkey rice bowl', 'ground_turkey', 'greek-oregano-lemon', 'bowl', 20, 25, 3, 42, 2, 'TURKEY — week 1. ''Bright and lean, nothing like the rest of the week. This is the variety night.'' Lisa''s meal.', '[{"item":"ground turkey 93/7","qty_per_person":8.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"cucumber","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true},{"item":"tomato","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"lemon","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true},{"item":"garlic","qty_per_person":2,"unit":"clove","store_section":"Produce","inferred":true},{"item":"dried oregano","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"rice","qty_per_person":0.5,"unit":"cup dry","store_section":"Pantry","inferred":true}]'::jsonb),
  ('garlic-herb-thighs', 'Garlic-herb skillet chicken thighs, green beans, potatoes', 'chicken_thigh', 'garlic-herb-italian', 'skillet', 20, 30, 3, 44, 2, 'Week 2. Same thigh as the chili-lime night, different profile and format — L5 in practice.', '[{"item":"chicken thigh, boneless skinless","qty_per_person":8,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"green beans","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"baby potatoes","qty_per_person":8,"unit":"oz","store_section":"Produce","inferred":true},{"item":"garlic powder","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"italian seasoning","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true}]'::jsonb),
  ('turkey-burgers', 'Turkey burger patties, roasted broccoli, baked potato', 'ground_turkey', 'smoked-paprika', 'patty', 15, 30, 3, 42, 2, 'TURKEY — week 2, replacing the steak night. Bun optional; the potato is already the carb. 93/7 ONLY.', '[{"item":"ground turkey 93/7","qty_per_person":8.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"broccoli","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"russet potato","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"smoked paprika","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"garlic powder","qty_per_person":0.5,"unit":"tsp","store_section":"Pantry","inferred":true}]'::jsonb),
  ('blackened-cod', 'Blackened cod or halibut, roasted broccoli, rice', 'cod_halibut', 'blackening', 'pan-seared', 15, 20, 2, 40, 3, 'FISH — week 2. BOUGHT ON THE SECOND TRIP, not the main shop. This is the meal that forces the mid-cycle top-up — learning L3. Cod is leaner than salmon, so weigh heavier.', '[{"item":"cod or halibut","qty_per_person":8.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"broccoli","qty_per_person":6,"unit":"oz","store_section":"Produce","inferred":true},{"item":"blackening seasoning","qty_per_person":1,"unit":"tsp","store_section":"Pantry","inferred":true},{"item":"rice","qty_per_person":0.5,"unit":"cup dry","store_section":"Pantry","inferred":true}]'::jsonb),
  ('soy-ginger-stirfry', 'Soy-ginger chicken breast and pepper stir-fry over rice', 'chicken_breast', 'soy-ginger', 'stir-fry', 25, 25, 2, 44, 2, 'Week 2. BREAST not thigh — deliberately, to keep a full pound of margin in the thigh bag. Active time is 25, close to the 30-min cap.', '[{"item":"chicken breast, boneless skinless","qty_per_person":6.5,"unit":"oz","store_section":"Meat & Seafood","inferred":false},{"item":"bell pepper","qty_per_person":1,"unit":"each","store_section":"Produce","inferred":true},{"item":"onion","qty_per_person":0.5,"unit":"each","store_section":"Produce","inferred":true},{"item":"fresh ginger","qty_per_person":1,"unit":"tsp","store_section":"Produce","inferred":true},{"item":"garlic","qty_per_person":2,"unit":"clove","store_section":"Produce","inferred":true},{"item":"low-sodium soy sauce","qty_per_person":1,"unit":"tbsp","store_section":"Pantry","inferred":true},{"item":"rice","qty_per_person":0.5,"unit":"cup dry","store_section":"Pantry","inferred":true}]'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, protein_cut = EXCLUDED.protein_cut, spice_profile = EXCLUDED.spice_profile,
  format = EXCLUDED.format, active_cook_minutes = EXCLUDED.active_cook_minutes, total_minutes = EXCLUDED.total_minutes,
  servings = EXCLUDED.servings, protein_g_per_person = EXCLUDED.protein_g_per_person,
  perishable_within_days = EXCLUDED.perishable_within_days, rotation_note = EXCLUDED.rotation_note,
  ingredients = EXCLUDED.ingredients;
